name: CI hugo

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run:
        push
      local_dir: public
      repo: binfer/binfer.github.io
      target_branch: master
